import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :just_travel, JustTravelWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, JustTravel.Finch

# Do not print debug messages in production
config :logger, level: :info

port = System.get_env("PORT") || 4000
host = System.get_env("PHX_HOST") || "localhost"
app = System.get_env("APP_NAME") || "just-travel"

config :just_travel, JustTravelWeb.Endpoint,
  url: [host: host, port: 4000, scheme: "https"],
  check_origin: [
    "https://just-travel.gigalixirapp.com/",
    "wss://just-travel.gigalixirapp.com/",
    "//just-travel.gigalixirapp.com/",
    "//localhost",
    "//*.just-travel.gigalixirapp.com/*",
    "//.#{app}.gigalixir.com/live",
    "//.#{app}.gigalixir.com:4000"
  ],
  port: port

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
